### ISSUE TITLE
Problem with url notification in Redsys, what file (php) is need to put on Redsys tpv administrator?

### ISSUE THREAD

**Issue by antoniocorres** [amnesty/civicrm-redsys#3]
Hello I need the file (.php) to put on Redsys TPV Adminisitrator to confirm the contribution to CiviCrm

The url notification which accept the payment and "complete" it in civicrm software.
Thanks

**Comment by ixiam** [comment]
Hi @antoniocorres , I don't understand what you are asking. 
IPN url is posted by the Payment Processor in the variables requested by Redsys, is that what you meant?
